### ISSUE TITLE
How to modify the name of default Admin user?

### ISSUE THREAD

**Issue by Kuanlin-Chen** [cloudbase/cloudbase-init#24] opened 2019-11-11 06:42 UTC
I tried to change the name of default admin user from `Admin` to `Administrator`, but it didn't take any effect, here is my cloudbase-init.conf:
```
[DEFAULT]
username=Administrator
groups=Administrators
inject_user_password=true
config_drive_raw_hhd=true
config_drive_cdrom=true
config_drive_vfat=true
bsdtar_path=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\bin\bsdtar.exe
mtools_path=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\bin\
verbose=true
debug=true
logdir=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\log\
logfile=cloudbase-init.log
default_log_levels=comtypes=INFO,suds=INFO,iso8601=WARN,requests=WARN
logging_serial_port_settings=
mtu_use_dhcp_config=true
ntp_use_dhcp_config=true
local_scripts_path=C:\Program Files\Cloudbase Solutions\Cloudbase-Init\LocalScripts\
```
**My main purpose is to enable `Administrator` account on my Windows10, and remove all other users**, and whatever I did so far, I got two account (Admin and Administrator) on my image, any suggestion?

**Comment by ader1990** [comment] 2019-11-11 11:16
Hello @Kuanlin-Chen ,

How did you create the Windows image? Using https://github.com/cloudbase/windows-openstack-imaging-tools/ ?

If possible, can you share the cloudbase-init logs?

Thank you.

**Comment by Kuanlin-Chen** [comment] 2019-11-12 02:06
@ader1990 Thanks for replying, I am using windows-openstack-imaging-tools, and I guess the `Admin` user is created by cloudbase-init while the instance booting the first time, so I tried not to install cloudbase-init, but it didn't work at all, the instance still have `Admin` account and `Administrator` account. This is not what I expected.

Would you mind telling me where the `Admin` user be created?

**Comment by ader1990** [comment] 2019-11-12 17:14
Please close this issue, as the problem is on the imaging tools configuration. will resume the explanation on the issue you created here: https://github.com/cloudbase/windows-openstack-imaging-tools/issues/327

**Closed as completed** 2019-11-13 07:34 UTC
